### ISSUE TITLE
Input format GNSS

### ISSUE THREAD

**Issue by goamberg** [aaronboda24/Loose-GNSS-IMU#1]
Hi

I came accross your gnss-imu fusion solution and wanted to test it out a little with my own data.
I saw the input files and was wondering if you have any more information on what format the GNSS Input file is? 
I have can produce .pos files (out of RTKLIB) quite easy, but there are nowhere near the 28 columns you have in your GNSS textfile.

Goam

**Comment by aaronboda24** [comment]
Hi Goam!
GNSS input parameters include:
- ECEF position XYZ components and corresponding variance-covariance
- Velocity XYZ components and corresponding variance-covariance
- Covariance of Position and Velocity (you can set these parameters as 0's)

Aaron.

**Comment by goamberg** [comment]
Thanks for the clarification.
To be more clear: I only need the 6 values (beside time): X,Y,Z and Vx,Vy,Vz?

ECEF position seems to be easy to get. Velocity no so much. Will figure it out.

thanks again

ps.
out of curiosity: with what system/GNSS modul did you produce the covariance data?

**Comment by aaronboda24** [comment]
- Apart from position and velocity, also consider having their corresponding variance-covariance (you can assign some constants). 
- I used my own GNSS module to produce the position, velocity and covariance. It uses relative positioning between rover and a single base station (with double-differenced carrier phase observations and ambiguity resolution).

**Comment by liyuebit** [comment]
Hello,
I am a beginner, and I am confused about some symbols.
(1) input data. Is Vel under the ECEF reference system?
(2) sf_eib. Is eib means boday frame --> ECI frame?
(3)sf_bib. Is bib means body frame –> body inertial frame?
(4)vel_eeb.Is eeb means body frame –> ECEF frame？

Looking forward to your reply.
Thank you very much.

**Comment by aaronboda24** [comment]
To answer your questions:
(1) input data. Is Vel under the ECEF reference system? - **Yes**
(2) sf_eib. Is eib means body frame --> ECI frame? - **body frame with respect to inertial frame, resolved in ecef frame**
(3)sf_bib. Is bib means body frame –> body inertial frame? - **body frame with respect to inertial frame, resolved in body frame**
(4)vel_eeb.Is eeb means body frame –> ECEF frame？- **body frame with respect to ecef frame, resolved in ecef frame**

**Comment by liyuebit** [comment]
OK, thank you very much. And I still have some questions.
(1) I can get vel data in NED frame (local navigation frame), so I have to transform it into ECEF frame, right? 
So I have to caculate **C_en** (NED to ECEF frame transform matrix), and **vel_eeb** =  **C_en** ***vel_navi**, right?

(2)One more question, you say that you use your own GNSS module to produce the position, velocity and covariance, so can you tell me which GNSS module you are using? And how does it get this covariance information? Do you have any tools or scripts to get convariance information from the observed data (position vel).

**Comment by aaronboda24** [comment]
To answer your questions:
(1) I can get vel data in NED frame (local navigation frame), so I have to transform it into ECEF frame, right? So I have to caculate C_en (NED to ECEF frame transform matrix), and vel_eeb = C_en *vel_navi, right? - **Yes, this is an ECEF implementation.**

(2)One more question, you say that you use your own GNSS module to produce the position, velocity and covariance, so can you tell me which GNSS module you are using? And how does it get this covariance information? Do you have any tools or scripts to get convariance information from the observed data (position vel). - **I am developing a sensor integration library for my lab, so I have a GNSS processing engine as part of that. I cannot share it. However you can use RTKLIB to generate position and std. deviation (sqrt of covariance). I sometimes use RTKLIB to validate my solution.**

**Comment by liyuebit** [comment]
OK, thank you very much.
Whitch navigation frame do you use in your project? ENU, I guess. But this function "**MatrixXd ecef2llfDCM(double lat, double lon)** " in your project returns the DCM means C_ecef2NED? (https://ww2.mathworks.cn/help/aeroblks/directioncosinematrixeceftonedtolatitudeandlongitude.html)
Is there something wrong?

**Comment by liyuebit** [comment]
So, you can use RTKLIB to generate position and std. deviation (sqrt of covariance), but how can you generate corresponding synchronous IMU data? 
Thank you.

**Comment by aaronboda24** [comment]
Firstly, you should open a new issue for your questions. This stream was opened for Input format. 
* Mechanization is in ECEF. Navigation frame NED is used to resolve attitude. I have some functions for ENU which have not been used. 
* I do not understand your question about "generating" IMU data. IMU data is obtained using an IMU sensor. Both GNSS and IMU measurements are appropriately time tagged. RTKLIB can only process your GNSS measurements. You can then use the RTKLIB GNSS solution as input here.
